name: Test Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: 'Test input'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Test Input
        run: |
          echo "Test Input: ${{ github.event.inputs.test_input }}"
